### ISSUE TITLE
Issue with throw Exception

### ISSUE THREAD

**Issue by spielcrypto** [pyrite-framework/pyrite-server#12]
I have a problem with the test that the login have to fail. It expect a 403 but I get a 500. 
The weird point is that the console watch prints `{ status: 403, error: 'login error' }`

Test:
```
lab.test('login have to fail with wrong password', (done) => {
    login.body = {username:"test", password: "failure21"};

    request(login)
    .catch((res) => {
      console.log(res.statusCode);
      Code.expect(res.statusCode).to.be.equal(403);
      done();
    });
  });
```
error:
```
Unhandled rejection Error: Expected 500 to equal specified value: 403
    at internals.Assertion.internals.equal (/home/razorpack/develop/socket-dancespiel/node_modules/code/lib/index.js:278:17)
    at request.catch (/home/razorpack/develop/socket-dancespiel/test/test/user.test.ts:27:41)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at tryCatcher (/home/razorpack/develop/socket-dancespiel/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/razorpack/develop/socket-dancespiel/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/razorpack/develop/socket-dancespiel/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/razorpack/develop/socket-dancespiel/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/razorpack/develop/socket-dancespiel/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/razorpack/develop/socket-dancespiel/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/razorpack/develop/socket-dancespiel/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/razorpack/develop/socket-dancespiel/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```
login code:
```
@Route("/login")
export class Login {
  @Post("/user")
  @Validation(loginValidation)
  async getAdmin(@Body login) {
    const user: any = await UserModel.findOne({username: login.username});
    const isvalid = await bcrypt.compare(login.password, user.password);
    if (!isvalid) {
      throw Exception(403, 'login error'); //it executes 
    }
    return createToken(user);
  }
}
```
This issue didn't happen before

**Comment by fagarbal** [comment]
fixed
